prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  server:
    nodeSelector:
      kubernetes.io/hostname: masternode00  # Replace <master-node-name> with your master node’s hostname
    securityContext:
      runAsUser: 0       # Replace with the actual user ID for running Prometheus
      runAsNonRoot: true
      runAsGroup: 0     # Replace with the actual group ID
      fsGroup: 0           # Replace with the filesystem group ID, typically the same as your runAsGroup
    persistentVolume:
      enabled: true
      existingClaim: "prometheus-usb-pvc"
      volumeName: "prometheus-usb-pv"
